# action.yml
name: 'SonarQube Scan'
description: 'Dotnet scanner for SonarQube'
inputs:
  option:  # id of input
    description: 'start or end scan'
    required: true
    default: 'start'
outputs:
  time: # id of output
    description: 'The time ${{ inputs.who-to-greet }}'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.option }}